
    create table activities (
       id int8 generated by default as identity,
        create_date timestamp not null,
        day int4 not null,
        description varchar(1000),
        title varchar(50),
        itinerary_id int8 not null,
        landmark_id int8,
        primary key (id)
    );

    create table comments (
       id int8 generated by default as identity,
        content varchar(1000) not null,
        create_date timestamp not null,
        rating int4 not null check (rating<=5 AND rating>=1),
        author_id int8,
        itinerary_id int8,
        primary key (id)
    );

    create table images (
       id int8 generated by default as identity,
        cloudinary_id varchar(255),
        image_url varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table itineraries (
       id int8 generated by default as identity,
        budget float8 check (budget>=0),
        create_date timestamp not null,
        description varchar(1000) not null,
        estimated_days int4 check (estimated_days<=365 AND estimated_days>=1),
        name varchar(50) not null,
        recommended_season varchar(255),
        status varchar(255) not null,
        author_id int8,
        image_id int8,
        primary key (id)
    );

    create table itinerary_visits (
       id int8 generated by default as identity,
        ip varchar(50),
        itinerary_id int8 not null,
        primary key (id)
    );

    create table landmark_visits (
       id int8 generated by default as identity,
        ip varchar(50),
        landmark_id int8 not null,
        primary key (id)
    );

    create table landmarks (
       id int8 generated by default as identity,
        category varchar(50),
        city varchar(100) not null,
        country varchar(100) not null,
        create_date timestamp,
        description varchar(1000) not null,
        email varchar(100),
        end_promotion_date timestamp,
        instagram varchar(300),
        latitude float8 check (latitude<=90 AND latitude>=-90),
        longitude float8 check (longitude<=180 AND longitude>=-180),
        name varchar(50) not null,
        phone varchar(50),
        price float8 check (price<=10000 AND price>=0),
        twitter varchar(300),
        website varchar(300),
        image_id int8,
        primary key (id)
    );

    create table roles (
       id int8 generated by default as identity,
        role_type varchar(255) not null,
        primary key (id)
    );

    create table secure_tokens (
       id int8 generated by default as identity,
        expite_at timestamp,
        timestamp timestamp,
        token varchar(255),
        user_id int8,
        primary key (id)
    );

    create table users (
       id int8 generated by default as identity,
        email varchar(255),
        enabled boolean not null,
        expiration_date timestamp,
        first_name varchar(50),
        last_name varchar(50),
        password varchar(50) not null,
        plan int4 not null,
        username varchar(50) not null,
        image_id int8,
        primary key (id)
    );

    create table users_roles (
       user_id int8 not null,
        role_id int8 not null,
        primary key (user_id, role_id)
    );
create index IDXqk4w2966vbyk2eya8nxco6wc2 on comments (create_date desc);
create index IDXakng6dnjupisnv7fgjxxya6pu on landmarks (country, city, name);

    alter table if exists secure_tokens 
       add constraint UK_dlvilc17p76edkguw5kd16xl5 unique (token);

    alter table if exists users 
       add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);

    alter table if exists activities 
       add constraint FKqf20g13dpp7lty39nddbfcxsd 
       foreign key (itinerary_id) 
       references itineraries;

    alter table if exists activities 
       add constraint FKdhfbuiumsiiqp4u78l9gvtvo6 
       foreign key (landmark_id) 
       references landmarks;

    alter table if exists comments 
       add constraint FKn2na60ukhs76ibtpt9burkm27 
       foreign key (author_id) 
       references users;

    alter table if exists comments 
       add constraint FKqj62p2aiyxhq3iucr4yh5jov3 
       foreign key (itinerary_id) 
       references itineraries;

    alter table if exists itineraries 
       add constraint FKlbl5jxlb4gwlwlfx2xmlfjmhc 
       foreign key (author_id) 
       references users;

    alter table if exists itineraries 
       add constraint FKow277v4ginrls4jpsgvj6x8c3 
       foreign key (image_id) 
       references images;

    alter table if exists itinerary_visits 
       add constraint FKo10ailgfbu73awm25t1re07y5 
       foreign key (itinerary_id) 
       references itineraries;

    alter table if exists landmark_visits 
       add constraint FK7325vhaen39hr33ncwqtq90n9 
       foreign key (landmark_id) 
       references landmarks;

    alter table if exists landmarks 
       add constraint FK42kmsmk00tru025fnrjuscylx 
       foreign key (image_id) 
       references images;

    alter table if exists secure_tokens 
       add constraint FKjee0y5bc9uy34jy86boygrjhl 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FK17herqt2to4hyl5q5r5ogbxk9 
       foreign key (image_id) 
       references images;

    alter table if exists users_roles 
       add constraint FKj6m8fwv7oqv74fcehir1a9ffy 
       foreign key (role_id) 
       references roles;

    alter table if exists users_roles 
       add constraint FK2o0jvgh89lemvvo17cbqvdxaa 
       foreign key (user_id) 
       references users;
